version: '3.8'

services:
  # Laravel Auth Service
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "9001:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:9001
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: auth_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  # Laravel Contact Service
  contact-service:
    build:
      context: ./contact-service
    container_name: contact-service
    ports:
      - "9002:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:9002
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: contact_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  # React Frontend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - contact-service

  # MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # API Gateway (NGINX)
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - auth-service
      - contact-service

volumes:
  mysql_data:
